### ISSUE TITLE
CV Review 

### ISSUE THREAD

**Issue by iAli22** [amrsekilly/amr-elsekilly-resume-template#1]
تسلم باشمهندس على الفرصة دي  كنت حابب من حضرتك 
تreview 
الcv 
ومتشوق جدًا اعرف تعليقاتك عليه وايه الي ممكن احسنه فيه

**Comment by amrsekilly** [comment]
Hello, Ali!

- First of all, I like your portfolio!
- Can you mention the name of the apps you built for this job? If it's a single app, you can say that you built G2K modern web app for example. Because this causes confusion sometimes, where the recruiter doesn't know whether you worked on the company's website or other apps there.
![Screen Shot 2021-04-30 at 10 15 44 PM](https://user-images.githubusercontent.com/4142276/116749700-9cf62b80-aa01-11eb-8464-58e25e36f110.png)

- You can reduce the height of this section by having 3 or 4 columns instead of 2, this will reduce the number of pages o the CV 
![Screen Shot 2021-04-30 at 10 18 11 PM](https://user-images.githubusercontent.com/4142276/116749928-f52d2d80-aa01-11eb-97b4-60baf97a48b8.png)

- The courses and education sections look good.
- I don't believe that the languages section is that important, but you can keep it because removing it won't reduce the number of pages of the CV.


I'll keep the issue open, in case you have any questions or need any other feedback. And feel free to close it once you reach the desired results.
