### ISSUE TITLE
CV Review

### ISSUE THREAD

**Issue by jojomak13** [amrsekilly/amr-elsekilly-resume-template#5]
شكرا جدا يا باشمهندس على الفرصة دية 
اتمنى انى حضرتك تعملى review لل cv
[Joseph Makram.pdf](https://github.com/amrsekilly/amr-elsekilly-resume-template/files/6407547/Joseph.Makram.pdf)

**Comment by amrsekilly** [comment]
Hello @jojomak13!

- I recommend moving this section below the about (intro) section 
![Screen Shot 2021-04-30 at 10 58 24 PM](https://user-images.githubusercontent.com/4142276/116753578-92d72b80-aa07-11eb-9b4b-e061a409a98a.png)

- I recommend moving the projects section above the education section. Because it's more important for companies and recruiters. 
- I recommend mentioning the technologies used for each project, and your role on each project, in addition to the years or dates for starting and ending the project. 
- I also recommend using Grammarly to make sure that there are no typos in the resume because I noticed a couple of them https://app.grammarly.com/

I'll keep the issue open, in case you have any questions or need any other feedback. And feel free to close it once you reach the desired results.

**Comment by jojomak13** [comment]
I am sorry for my late please check it again after editing, thanks in advance
[Joseph Makram.pdf](https://github.com/amrsekilly/amr-elsekilly-resume-template/files/6448548/Joseph.Makram.pdf)

**Comment by amrsekilly** [comment]
@jojomak13 no worries! It looks amazing 🔥 

I recommend changing `A passion web developer with 3 years of experiences and a computer science student at HTI.` to

`A passionate full-stack web developer with 3 years of experience, and a computer science student at HTI.`
